//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PubSubDomain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PubSubDomain.Resources.FieldText", typeof(FieldText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] [{1:d MMM yyyy HH:mm:ss}]: {2}.
        /// </summary>
        public static string ChatHistoryFormat {
            get {
                return ResourceManager.GetString("ChatHistoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Service 1.
        /// </summary>
        public static string DefaultPublisherName {
            get {
                return ResourceManager.GetString("DefaultPublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input message..
        /// </summary>
        public static string ErrorEmptyMessage {
            get {
                return ResourceManager.GetString("ErrorEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill publisher..
        /// </summary>
        public static string ErrorEmptyPublisher {
            get {
                return ResourceManager.GetString("ErrorEmptyPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input subscriber..
        /// </summary>
        public static string ErrorEmptySubsriber {
            get {
                return ResourceManager.GetString("ErrorEmptySubsriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is subscribing..
        /// </summary>
        public static string SubscribingFormat {
            get {
                return ResourceManager.GetString("SubscribingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is unsubscribing..
        /// </summary>
        public static string UnsubscribingFormat {
            get {
                return ResourceManager.GetString("UnsubscribingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:dd MMM yyyy HH:mm:ss}]: You are subscribing..
        /// </summary>
        public static string YouAreSubscribingFormat {
            get {
                return ResourceManager.GetString("YouAreSubscribingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0:dd MMM yyyy HH:mm:ss}]: You are unsubscribing..
        /// </summary>
        public static string YouAreUnsubscribingFormat {
            get {
                return ResourceManager.GetString("YouAreUnsubscribingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [You] [{0:dd MMM yyyy HH:mm:ss}]: {1}.
        /// </summary>
        public static string YouSendMessageFormat {
            get {
                return ResourceManager.GetString("YouSendMessageFormat", resourceCulture);
            }
        }
    }
}
